/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from './app';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/router/src/directives/router_link';
import * as import12 from '@angular/router/src/directives/router_link_active';
import * as import13 from '@angular/router/src/directives/router_outlet';
import * as import14 from '@angular/core/src/linker/query_list';
import * as import15 from '@angular/router/src/router';
import * as import16 from '@angular/router/src/router_state';
import * as import17 from '@angular/common/src/location/location_strategy';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/router/src/router_outlet_map';
import * as import20 from '@angular/core/src/linker/component_factory_resolver';
import * as import21 from '@angular/core/src/security';
const nodeDebugInfos_App_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.App],import1.App,{})];
var renderType_App_Host:import2.RenderComponentType = (null as any);
class _View_App_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _App_0_4:import1.App;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_App_Host0,renderType_App_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_App_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_App0(this.viewUtils,this.injector(0),this._appEl_0);
    this._App_0_4 = new import1.App();
    this._appEl_0.initComponent(this._App_0_4,[],compView_0);
    compView_0.create(this._App_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.App) && (0 === requestNodeIndex))) { return this._App_0_4; }
    return notFoundResult;
  }
}
function viewFactory_App_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_App_Host === (null as any))) { (renderType_App_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_App_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppNgFactory:import10.ComponentFactory<import1.App> = new import10.ComponentFactory<import1.App>('app',viewFactory_App_Host0,import1.App);
const styles_App:any[] = [];
const nodeDebugInfos_App0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import11.RouterLinkWithHref,
    import12.RouterLinkActive
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import13.RouterOutlet],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_App:import2.RenderComponentType = (null as any);
class _View_App0 extends import3.DebugAppView<import1.App> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _RouterLinkWithHref_7_3:import11.RouterLinkWithHref;
  _RouterLinkActive_7_4:import12.RouterLinkActive;
  _query_RouterLink_7_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_7_1:import14.QueryList<any>;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _el_11:any;
  _RouterLinkWithHref_11_3:import11.RouterLinkWithHref;
  _RouterLinkActive_11_4:import12.RouterLinkActive;
  _query_RouterLink_11_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_11_1:import14.QueryList<any>;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _RouterLinkWithHref_15_3:import11.RouterLinkWithHref;
  _RouterLinkActive_15_4:import12.RouterLinkActive;
  _query_RouterLink_15_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_15_1:import14.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  _RouterLinkWithHref_24_3:import11.RouterLinkWithHref;
  _RouterLinkActive_24_4:import12.RouterLinkActive;
  _query_RouterLink_24_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_24_1:import14.QueryList<any>;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _RouterLinkWithHref_28_3:import11.RouterLinkWithHref;
  _RouterLinkActive_28_4:import12.RouterLinkActive;
  _query_RouterLink_28_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_28_1:import14.QueryList<any>;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _el_32:any;
  _RouterLinkWithHref_32_3:import11.RouterLinkWithHref;
  _RouterLinkActive_32_4:import12.RouterLinkActive;
  _query_RouterLink_32_0:import14.QueryList<any>;
  _query_RouterLinkWithHref_32_1:import14.QueryList<any>;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import4.AppElement;
  _RouterOutlet_36_5:import13.RouterOutlet;
  _text_37:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_App0,renderType_App,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_App0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(0,0,0));
    this._el_1 = this.renderer.createElement(parentRenderNode,'h1',this.debug(1,1,2));
    this._text_2 = this.renderer.createText(this._el_1,'Hello Angular Universal App',this.debug(2,1,6));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(3,1,38));
    this._el_4 = this.renderer.createElement(parentRenderNode,'ul',this.debug(4,2,2));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',this.debug(5,2,6));
    this._el_6 = this.renderer.createElement(this._el_4,'li',this.debug(6,3,4));
    this._el_7 = this.renderer.createElement(this._el_6,'a',this.debug(7,3,8));
    this.renderer.setElementAttribute(this._el_7,'routerLink','');
    this.renderer.setElementAttribute(this._el_7,'routerLinkActive','active');
    this._RouterLinkWithHref_7_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_7_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_7),this.renderer);
    this._query_RouterLink_7_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_7_1 = new import14.QueryList<any>();
    this._text_8 = this.renderer.createText(this._el_7,'Angular Universal',this.debug(8,3,51));
    this._text_9 = this.renderer.createText(this._el_4,'\n    ',this.debug(9,3,77));
    this._el_10 = this.renderer.createElement(this._el_4,'li',this.debug(10,4,4));
    this._el_11 = this.renderer.createElement(this._el_10,'a',this.debug(11,4,8));
    this.renderer.setElementAttribute(this._el_11,'routerLink','home');
    this.renderer.setElementAttribute(this._el_11,'routerLinkActive','active');
    this._RouterLinkWithHref_11_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_11_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_11),this.renderer);
    this._query_RouterLink_11_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_11_1 = new import14.QueryList<any>();
    this._text_12 = this.renderer.createText(this._el_11,'Home',this.debug(12,4,55));
    this._text_13 = this.renderer.createText(this._el_4,'\n    ',this.debug(13,4,68));
    this._el_14 = this.renderer.createElement(this._el_4,'li',this.debug(14,5,4));
    this._el_15 = this.renderer.createElement(this._el_14,'a',this.debug(15,5,8));
    this.renderer.setElementAttribute(this._el_15,'routerLink','about');
    this.renderer.setElementAttribute(this._el_15,'routerLinkActive','active');
    this._RouterLinkWithHref_15_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_15_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_15),this.renderer);
    this._query_RouterLink_15_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_15_1 = new import14.QueryList<any>();
    this._text_16 = this.renderer.createText(this._el_15,'About',this.debug(16,5,56));
    this._text_17 = this.renderer.createText(this._el_4,'\n  ',this.debug(17,5,70));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(18,6,7));
    this._el_19 = this.renderer.createElement(parentRenderNode,'hr',this.debug(19,7,2));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(20,7,6));
    this._el_21 = this.renderer.createElement(parentRenderNode,'ul',this.debug(21,8,2));
    this._text_22 = this.renderer.createText(this._el_21,'\n    ',this.debug(22,8,6));
    this._el_23 = this.renderer.createElement(this._el_21,'li',this.debug(23,9,4));
    this._el_24 = this.renderer.createElement(this._el_23,'a',this.debug(24,9,8));
    this.renderer.setElementAttribute(this._el_24,'routerLink','a');
    this.renderer.setElementAttribute(this._el_24,'routerLinkActive','active');
    this._RouterLinkWithHref_24_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_24_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_24),this.renderer);
    this._query_RouterLink_24_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_24_1 = new import14.QueryList<any>();
    this._text_25 = this.renderer.createText(this._el_24,'A Component',this.debug(25,9,52));
    this._text_26 = this.renderer.createText(this._el_21,'\n    ',this.debug(26,9,72));
    this._el_27 = this.renderer.createElement(this._el_21,'li',this.debug(27,10,4));
    this._el_28 = this.renderer.createElement(this._el_27,'a',this.debug(28,10,8));
    this.renderer.setElementAttribute(this._el_28,'routerLink','b');
    this.renderer.setElementAttribute(this._el_28,'routerLinkActive','active');
    this._RouterLinkWithHref_28_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_28_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_28),this.renderer);
    this._query_RouterLink_28_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_28_1 = new import14.QueryList<any>();
    this._text_29 = this.renderer.createText(this._el_28,'B Component',this.debug(29,10,52));
    this._text_30 = this.renderer.createText(this._el_21,'\n    ',this.debug(30,10,72));
    this._el_31 = this.renderer.createElement(this._el_21,'li',this.debug(31,11,4));
    this._el_32 = this.renderer.createElement(this._el_31,'a',this.debug(32,11,8));
    this.renderer.setElementAttribute(this._el_32,'routerLink','c');
    this.renderer.setElementAttribute(this._el_32,'routerLinkActive','active');
    this._RouterLinkWithHref_32_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_32_4 = new import12.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_32),this.renderer);
    this._query_RouterLink_32_0 = new import14.QueryList<any>();
    this._query_RouterLinkWithHref_32_1 = new import14.QueryList<any>();
    this._text_33 = this.renderer.createText(this._el_32,'C Component',this.debug(33,11,52));
    this._text_34 = this.renderer.createText(this._el_21,'\n  ',this.debug(34,11,72));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(35,12,7));
    this._el_36 = this.renderer.createElement(parentRenderNode,'router-outlet',this.debug(36,13,2));
    this._appEl_36 = new import4.AppElement(36,(null as any),this,this._el_36);
    this._RouterOutlet_36_5 = new import13.RouterOutlet(this.parentInjector.get(import19.RouterOutletMap),this._appEl_36.vcRef,this.parentInjector.get(import20.ComponentFactoryResolver),(null as any));
    this._text_37 = this.renderer.createText(parentRenderNode,'\n  ',this.debug(37,13,33));
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_24,'click',this.eventHandler(this._handle_click_24_0.bind(this)));
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_28,'click',this.eventHandler(this._handle_click_28_0.bind(this)));
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_32,'click',this.eventHandler(this._handle_click_32_0.bind(this)));
    this._expr_21 = import8.UNINITIALIZED;
    this._expr_22 = import8.UNINITIALIZED;
    this._expr_23 = import8.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.RouterLinkWithHref) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkWithHref_7_3; }
    if (((token === import12.RouterLinkActive) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkActive_7_4; }
    if (((token === import11.RouterLinkWithHref) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkWithHref_11_3; }
    if (((token === import12.RouterLinkActive) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkActive_11_4; }
    if (((token === import11.RouterLinkWithHref) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkWithHref_15_3; }
    if (((token === import12.RouterLinkActive) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkActive_15_4; }
    if (((token === import11.RouterLinkWithHref) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._RouterLinkWithHref_24_3; }
    if (((token === import12.RouterLinkActive) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._RouterLinkActive_24_4; }
    if (((token === import11.RouterLinkWithHref) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._RouterLinkWithHref_28_3; }
    if (((token === import12.RouterLinkActive) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._RouterLinkActive_28_4; }
    if (((token === import11.RouterLinkWithHref) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._RouterLinkWithHref_32_3; }
    if (((token === import12.RouterLinkActive) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._RouterLinkActive_32_4; }
    if (((token === import13.RouterOutlet) && (36 === requestNodeIndex))) { return this._RouterOutlet_36_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    this.debug(7,3,8);
    changes = (null as any);
    this.debug(7,3,11);
    const currVal_1:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_7_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_7_3.ngOnChanges(changes); }
    this.debug(7,3,8);
    changes = (null as any);
    this.debug(7,3,25);
    const currVal_3:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_7_4.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_7_4.ngOnChanges(changes); }
    this.debug(11,4,8);
    changes = (null as any);
    this.debug(11,4,11);
    const currVal_5:any = 'home';
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._RouterLinkWithHref_11_3.routerLink = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_11_3.ngOnChanges(changes); }
    this.debug(11,4,8);
    changes = (null as any);
    this.debug(11,4,29);
    const currVal_7:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkActive_11_4.routerLinkActive = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_11_4.ngOnChanges(changes); }
    this.debug(15,5,8);
    changes = (null as any);
    this.debug(15,5,11);
    const currVal_9:any = 'about';
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._RouterLinkWithHref_15_3.routerLink = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_15_3.ngOnChanges(changes); }
    this.debug(15,5,8);
    changes = (null as any);
    this.debug(15,5,30);
    const currVal_11:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._RouterLinkActive_15_4.routerLinkActive = currVal_11;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_11,currVal_11);
      this._expr_11 = currVal_11;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_15_4.ngOnChanges(changes); }
    this.debug(24,9,8);
    changes = (null as any);
    this.debug(24,9,11);
    const currVal_13:any = 'a';
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._RouterLinkWithHref_24_3.routerLink = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_24_3.ngOnChanges(changes); }
    this.debug(24,9,8);
    changes = (null as any);
    this.debug(24,9,26);
    const currVal_15:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._RouterLinkActive_24_4.routerLinkActive = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_24_4.ngOnChanges(changes); }
    this.debug(28,10,8);
    changes = (null as any);
    this.debug(28,10,11);
    const currVal_17:any = 'b';
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._RouterLinkWithHref_28_3.routerLink = currVal_17;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_17,currVal_17);
      this._expr_17 = currVal_17;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_28_3.ngOnChanges(changes); }
    this.debug(28,10,8);
    changes = (null as any);
    this.debug(28,10,26);
    const currVal_19:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._RouterLinkActive_28_4.routerLinkActive = currVal_19;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_19,currVal_19);
      this._expr_19 = currVal_19;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_28_4.ngOnChanges(changes); }
    this.debug(32,11,8);
    changes = (null as any);
    this.debug(32,11,11);
    const currVal_21:any = 'c';
    if (import5.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._RouterLinkWithHref_32_3.routerLink = currVal_21;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_21,currVal_21);
      this._expr_21 = currVal_21;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_32_3.ngOnChanges(changes); }
    this.debug(32,11,8);
    changes = (null as any);
    this.debug(32,11,26);
    const currVal_23:any = 'active';
    if (import5.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._RouterLinkActive_32_4.routerLinkActive = currVal_23;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import8.SimpleChange(this._expr_23,currVal_23);
      this._expr_23 = currVal_23;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_32_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_7_0.dirty) {
        this._query_RouterLink_7_0.reset([]);
        this._RouterLinkActive_7_4.links = this._query_RouterLink_7_0;
        this._query_RouterLink_7_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_7_1.dirty) {
        this._query_RouterLinkWithHref_7_1.reset([this._RouterLinkWithHref_7_3]);
        this._RouterLinkActive_7_4.linksWithHrefs = this._query_RouterLinkWithHref_7_1;
        this._query_RouterLinkWithHref_7_1.notifyOnChanges();
      }
      if (this._query_RouterLink_11_0.dirty) {
        this._query_RouterLink_11_0.reset([]);
        this._RouterLinkActive_11_4.links = this._query_RouterLink_11_0;
        this._query_RouterLink_11_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_11_1.dirty) {
        this._query_RouterLinkWithHref_11_1.reset([this._RouterLinkWithHref_11_3]);
        this._RouterLinkActive_11_4.linksWithHrefs = this._query_RouterLinkWithHref_11_1;
        this._query_RouterLinkWithHref_11_1.notifyOnChanges();
      }
      if (this._query_RouterLink_15_0.dirty) {
        this._query_RouterLink_15_0.reset([]);
        this._RouterLinkActive_15_4.links = this._query_RouterLink_15_0;
        this._query_RouterLink_15_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_15_1.dirty) {
        this._query_RouterLinkWithHref_15_1.reset([this._RouterLinkWithHref_15_3]);
        this._RouterLinkActive_15_4.linksWithHrefs = this._query_RouterLinkWithHref_15_1;
        this._query_RouterLinkWithHref_15_1.notifyOnChanges();
      }
      if (this._query_RouterLink_24_0.dirty) {
        this._query_RouterLink_24_0.reset([]);
        this._RouterLinkActive_24_4.links = this._query_RouterLink_24_0;
        this._query_RouterLink_24_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_24_1.dirty) {
        this._query_RouterLinkWithHref_24_1.reset([this._RouterLinkWithHref_24_3]);
        this._RouterLinkActive_24_4.linksWithHrefs = this._query_RouterLinkWithHref_24_1;
        this._query_RouterLinkWithHref_24_1.notifyOnChanges();
      }
      if (this._query_RouterLink_28_0.dirty) {
        this._query_RouterLink_28_0.reset([]);
        this._RouterLinkActive_28_4.links = this._query_RouterLink_28_0;
        this._query_RouterLink_28_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_28_1.dirty) {
        this._query_RouterLinkWithHref_28_1.reset([this._RouterLinkWithHref_28_3]);
        this._RouterLinkActive_28_4.linksWithHrefs = this._query_RouterLinkWithHref_28_1;
        this._query_RouterLinkWithHref_28_1.notifyOnChanges();
      }
      if (this._query_RouterLink_32_0.dirty) {
        this._query_RouterLink_32_0.reset([]);
        this._RouterLinkActive_32_4.links = this._query_RouterLink_32_0;
        this._query_RouterLink_32_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_32_1.dirty) {
        this._query_RouterLinkWithHref_32_1.reset([this._RouterLinkWithHref_32_3]);
        this._RouterLinkActive_32_4.linksWithHrefs = this._query_RouterLinkWithHref_32_1;
        this._query_RouterLinkWithHref_32_1.notifyOnChanges();
      }
      this.debug(7,3,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_7_4.ngAfterContentInit(); }
      this.debug(11,4,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_11_4.ngAfterContentInit(); }
      this.debug(15,5,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_15_4.ngAfterContentInit(); }
      this.debug(24,9,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_24_4.ngAfterContentInit(); }
      this.debug(28,10,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_28_4.ngAfterContentInit(); }
      this.debug(32,11,8);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_32_4.ngAfterContentInit(); }
    }
    this.debug(7,3,8);
    const currVal_2:any = this._RouterLinkWithHref_7_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_7,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.debug(11,4,8);
    const currVal_6:any = this._RouterLinkWithHref_11_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_11,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_6));
      this._expr_6 = currVal_6;
    }
    this.debug(15,5,8);
    const currVal_10:any = this._RouterLinkWithHref_15_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_15,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_10));
      this._expr_10 = currVal_10;
    }
    this.debug(24,9,8);
    const currVal_14:any = this._RouterLinkWithHref_24_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_24,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_14));
      this._expr_14 = currVal_14;
    }
    this.debug(28,10,8);
    const currVal_18:any = this._RouterLinkWithHref_28_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementProperty(this._el_28,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_18));
      this._expr_18 = currVal_18;
    }
    this.debug(32,11,8);
    const currVal_22:any = this._RouterLinkWithHref_32_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementProperty(this._el_32,'href',this.viewUtils.sanitizer.sanitize(import21.SecurityContext.URL,currVal_22));
      this._expr_22 = currVal_22;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(7,3,8);
    this._RouterLinkWithHref_7_3.ngOnDestroy();
    this._RouterLinkActive_7_4.ngOnDestroy();
    this.debug(11,4,8);
    this._RouterLinkWithHref_11_3.ngOnDestroy();
    this._RouterLinkActive_11_4.ngOnDestroy();
    this.debug(15,5,8);
    this._RouterLinkWithHref_15_3.ngOnDestroy();
    this._RouterLinkActive_15_4.ngOnDestroy();
    this.debug(24,9,8);
    this._RouterLinkWithHref_24_3.ngOnDestroy();
    this._RouterLinkActive_24_4.ngOnDestroy();
    this.debug(28,10,8);
    this._RouterLinkWithHref_28_3.ngOnDestroy();
    this._RouterLinkActive_28_4.ngOnDestroy();
    this.debug(32,11,8);
    this._RouterLinkWithHref_32_3.ngOnDestroy();
    this._RouterLinkActive_32_4.ngOnDestroy();
    this.debug(36,13,2);
    this._RouterOutlet_36_5.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(7,3,8);
    const pd_0:any = ((<any>this._RouterLinkWithHref_7_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(11,4,8);
    const pd_0:any = ((<any>this._RouterLinkWithHref_11_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(15,5,8);
    const pd_0:any = ((<any>this._RouterLinkWithHref_15_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(24,9,8);
    const pd_0:any = ((<any>this._RouterLinkWithHref_24_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(28,10,8);
    const pd_0:any = ((<any>this._RouterLinkWithHref_28_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(32,11,8);
    const pd_0:any = ((<any>this._RouterLinkWithHref_32_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_App0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.App> {
  if ((renderType_App === (null as any))) { (renderType_App = viewUtils.createRenderComponentType('/Users/albatrosary/Sandbox/universal-starter/src/app/app.ts class App - inline template',0,import9.ViewEncapsulation.None,styles_App,{})); }
  return new _View_App0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_Home_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.Home],import1.Home,{})];
var renderType_Home_Host:import2.RenderComponentType = (null as any);
class _View_Home_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _Home_0_4:import1.Home;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Home_Host0,renderType_Home_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Home_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('home',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Home0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Home_0_4 = new import1.Home();
    this._appEl_0.initComponent(this._Home_0_4,[],compView_0);
    compView_0.create(this._Home_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.Home) && (0 === requestNodeIndex))) { return this._Home_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Home_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_Home_Host === (null as any))) { (renderType_Home_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_Home_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomeNgFactory:import10.ComponentFactory<import1.Home> = new import10.ComponentFactory<import1.Home>('home',viewFactory_Home_Host0,import1.Home);
const styles_Home:any[] = [];
const nodeDebugInfos_Home0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([],(null as any),{})];
var renderType_Home:import2.RenderComponentType = (null as any);
class _View_Home0 extends import3.DebugAppView<import1.Home> {
  _text_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Home0,renderType_Home,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Home0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'Home component',this.debug(0,0,0));
    this.init([],[this._text_0],[],[]);
    return (null as any);
  }
}
export function viewFactory_Home0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.Home> {
  if ((renderType_Home === (null as any))) { (renderType_Home = viewUtils.createRenderComponentType('/Users/albatrosary/Sandbox/universal-starter/src/app/app.ts class Home - inline template',0,import9.ViewEncapsulation.None,styles_Home,{})); }
  return new _View_Home0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_About_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.About],import1.About,{})];
var renderType_About_Host:import2.RenderComponentType = (null as any);
class _View_About_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _About_0_4:import1.About;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_About_Host0,renderType_About_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_About_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('about',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_About0(this.viewUtils,this.injector(0),this._appEl_0);
    this._About_0_4 = new import1.About();
    this._appEl_0.initComponent(this._About_0_4,[],compView_0);
    compView_0.create(this._About_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.About) && (0 === requestNodeIndex))) { return this._About_0_4; }
    return notFoundResult;
  }
}
function viewFactory_About_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_About_Host === (null as any))) { (renderType_About_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_About_Host0(viewUtils,parentInjector,declarationEl);
}
export const AboutNgFactory:import10.ComponentFactory<import1.About> = new import10.ComponentFactory<import1.About>('about',viewFactory_About_Host0,import1.About);
const styles_About:any[] = [];
const nodeDebugInfos_About0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([],(null as any),{})];
var renderType_About:import2.RenderComponentType = (null as any);
class _View_About0 extends import3.DebugAppView<import1.About> {
  _text_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_About0,renderType_About,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_About0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'About component',this.debug(0,0,0));
    this.init([],[this._text_0],[],[]);
    return (null as any);
  }
}
export function viewFactory_About0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.About> {
  if ((renderType_About === (null as any))) { (renderType_About = viewUtils.createRenderComponentType('/Users/albatrosary/Sandbox/universal-starter/src/app/app.ts class About - inline template',0,import9.ViewEncapsulation.None,styles_About,{})); }
  return new _View_About0(viewUtils,parentInjector,declarationEl);
}